apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
    module: test
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echo
    module: test
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
      module: test
  replicas: 3
  template:
    metadata:
      labels:
        app: echo
        module: test
    spec:
      containers:
      - name: echo
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
