apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    module: test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hello
    module: test
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    module: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      module: test
  template:
    metadata:
      labels:
        app: hello
        module: test
    spec:
      containers:
      - name: hello
        image: paulbouwer/hello-kubernetes:1.7
        ports:
        - containerPort: 8080
