---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-ingress
route:
  strip_path: true
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - host: api.kong.local
    http:
      paths:
      - path: /foo
        backend:
          serviceName: echoserver
          servicePort: 80
      - path: /bar
        backend:
          serviceName: helloserver
          servicePort: 80